const CONFIG = {
	TIME_STEP: 0.05,
	CANVAS_CONFIG: {
		CANVAS_ID: 'trafficSimulator',
		CANVAS_WIDTH: 1500,
		CANVAS_HEIGHT: 100,
	},
	MAX_ROAD_LENGTH: 1000,
	
	/* TODO: Set defaults */
	VEHICLE_TYPE: {
		VIRTUAL: 'virtual',
		CAR: 'car',
		VAN: 'van',
		TRUCK: 'truck',
		CUSTOM: 'custom'
	},
	DEFAULT_VEHICLE_OPTS: {
		CAR: {
			VEHICLE_LENGTH: [],
			INITIAL_POSITION: 0,
			INITIAL_VELOCITY: 0,
			DESIRED_VELOCITY: [],
			SAFE_TIME_HEADWAY: [],
			MAX_ACCELERATION: [],
			DESIRED_DECELERATION: [],
			JAM_DISTANCE: [],
			ACCELERATION_EXPONENT: []
		},
		VAN: {
			VEHICLE_LENGTH: [],
			INITIAL_POSITION: 0,
			INITIAL_VELOCITY: 0,
			DESIRED_VELOCITY: [],
			SAFE_TIME_HEADWAY: [],
			MAX_ACCELERATION: [],
			DESIRED_DECELERATION: [],
			JAM_DISTANCE: [],
			ACCELERATION_EXPONENT: []
		},
		TRUCK: {
			VEHICLE_LENGTH: [],
			INITIAL_POSITION: 0,
			INITIAL_VELOCITY: 0,
			DESIRED_VELOCITY: [],
			SAFE_TIME_HEADWAY: [],
			MAX_ACCELERATION: [],
			DESIRED_DECELERATION: [],
			JAM_DISTANCE: [],
			ACCELERATION_EXPONENT: []
		}
	},
	BEHAVIOUR_TYPE: {
		IS_SPAWNED: 'isSpawned',
		DESIRED_VELOCITY: 'desiredVelocity',
		SAFE_TIME_HEADWAY: 'safeTimeHeadway',
		MAX_ACCELERATION: 'maxAcceleration',
		DESIRED_DECELERATION: 'desiredDeceleration',
		JAM_DISTANCE: 'jamDistance',
		ACCELERATION_EXPONENT: 'accelerationExponent'
	},
};

module.exports = CONFIG;